# Generated by Django 2.1 on 2019-10-19 08:15

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('auth_User', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.CharField(max_length=4)),
                ('address1', models.CharField(max_length=6)),
                ('self_introduction', models.CharField(max_length=200)),
                ('favorite_store1', models.CharField(max_length=200, null=True, verbose_name='お気に入り店舗1')),
                ('favorite_store2', models.CharField(max_length=200, null=True, verbose_name='お気に入り店舗2')),
                ('favorite_store3', models.CharField(max_length=200, null=True, verbose_name='お気に入り店舗3')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 19, 17, 15, 7, 70767), verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最終ログイン')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='店舗名')),
                ('image', models.ImageField(upload_to='images/', verbose_name='画像')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('address', models.CharField(max_length=50, verbose_name='住所')),
                ('bussiness_hours', models.CharField(max_length=10, verbose_name='営業時間')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='緯度')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='経度')),
            ],
            options={
                'verbose_name': '店名',
                'verbose_name_plural': '店名',
            },
        ),
    ]
