# Generated by Django 2.1 on 2019-10-15 15:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('auth_User', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.CharField(max_length=4)),
                ('address1', models.CharField(max_length=6)),
                ('self_introduction', models.CharField(max_length=200)),
                ('favorite_store1', models.CharField(max_length=200, null=True, verbose_name='お気に入り店舗1')),
                ('favorite_store2', models.CharField(max_length=200, null=True, verbose_name='お気に入り店舗2')),
                ('favorite_store3', models.CharField(max_length=200, null=True, verbose_name='お気に入り店舗3')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 10, 16, 0, 11, 21, 648141), verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最終ログイン')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='画像')),
            ],
        ),
    ]
