# Generated by Django 2.1 on 2019-10-03 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('gender', models.IntegerField(blank=True, choices=[(1, '男'), (2, '女'), (3, 'その他')], null=True, verbose_name='性別')),
                ('age', models.IntegerField(choices=[(10, '10代'), (20, '20代'), (30, '30代'), (40, '40代'), (50, '50代'), (60, '60代'), (70, '70代'), (80, '80代'), (90, '90代')], verbose_name='年齢')),
                ('zip_code', models.CharField(blank=True, max_length=8, verbose_name='郵便番号')),
                ('address1', models.CharField(blank=True, max_length=40, verbose_name='都道府県')),
                ('address2', models.CharField(blank=True, max_length=40, verbose_name='市区町村番地')),
                ('self_introduction', models.CharField(max_length=200, null=True, verbose_name='自己紹介')),
                ('favorite_store1', models.CharField(max_length=200, null=True, verbose_name='お気に入り店舗1')),
                ('favorite_store2', models.CharField(max_length=200, null=True, verbose_name='お気に入り店舗2')),
                ('favorite_store3', models.CharField(max_length=200, null=True, verbose_name='お気に入り店舗3')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最終ログイン')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
