# Generated by Django 2.1 on 2019-10-21 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 14, 58, 58, 501671), verbose_name='登録日時'),
        ),
    ]
