# Generated by Django 2.1 on 2019-10-21 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0002_auto_20191021_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 14, 59, 6, 322924), verbose_name='登録日時'),
        ),
    ]
