# Generated by Django 2.1 on 2019-10-11 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0002_auto_20191011_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 11, 23, 46, 43, 317244), verbose_name='登録日時'),
        ),
    ]
