# Generated by Django 2.1 on 2019-10-03 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0002_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 17, 2, 29, 15193), verbose_name='登録日時'),
        ),
    ]
