# Generated by Django 2.1 on 2019-10-04 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0003_auto_20191003_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 4, 21, 24, 50, 588949), verbose_name='登録日時'),
        ),
    ]
