# Generated by Django 2.1 on 2019-10-21 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrescue', '0003_auto_20191021_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 15, 0, 21, 970795), verbose_name='登録日時'),
        ),
    ]
